language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      script:
        - swift test

    - os: linux
      language: generic
      sudo: required
      dist: trusty
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv global 5.1.1
      script:
        - swift test
